apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.3.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: monitoring
  values:
    alertmanager:
      alertmanagerSpec:
        logFormat: json
        logLevel: warn
    prometheus:
      prometheusSpec:
        logFormat: json
        logLevel: warn
