apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-prometheus-stack-helmrelease.yaml
- prometheus-community-helmrepo.yaml

configMapGenerator:
  - name: flux-dashboards
    namespace: flux-system
    files:
      - configs/control-plane.json
      - configs/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
